### ISSUE TITLE
Final assessment Grades and Student Report Generation Tool

### ISSUE THREAD

**Issue by muslimfaisal** [frappe/education#111]
Hello Jannat, when we try the Final Assessment Grades option, it gives and error.

Also the Student Report Generation Tool does not work. Seems like the problem is the same and both options are not working because of that issue. 

Details of the error for Final Assessment Grades:

![image](https://user-images.githubusercontent.com/50970263/221782180-a7217c7a-78cb-443d-8b45-ccf7e6b91d36.png)

### App Versions
```
{
	"erpnext": "13.36.5",
	"frappe": "13.39.1"
}
```
### Route
```
query-report/Final Assessment Grades
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1457, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 256, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 767, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 90, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 71, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 148, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 165, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/education/report/final_assessment_grades/final_assessment_grades.py", line 42, in execute
    student_row["grade_" + scrub_course] = assessment_result[student][course][assessment_group][
KeyError: 'grade'

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Final Assessment Grades",
		"filters": "{\"academic_year\":\"۱۴۰۱-۱۴۰۲\",\"student_group\":\"لمعه یک (گروه 8)\",\"assessment_group\":\"1401-1402\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "KeyError: 'grade'"
}
```

**Comment by muslimfaisal** [comment]
Hello Jannat, I questioned about this in the webinar today.
I am not really a programmer, so will not request a pull. But am very keen to get this resolved.

**Comment by muslimfaisal** [comment]
@pateljannat, is this something that might be resolved in the next few months?
Or should we not rely on this for the end of year results in June?

**Comment by pateljannat** [comment]
@muslimfaisal Both reports are working fine for me. 

<img width="1336" alt="Screenshot 2023-03-27 at 5 59 17 PM" src="https://user-images.githubusercontent.com/31363128/227942064-eb3add44-1fff-4ecb-9027-0c1474a4d775.png">

From the information you shared, it seems like you are still on v13. I recommend that you migrate to v14, as the app has been separated from ERPNext since.

**Comment by pateljannat** [comment]
@muslimfaisal Both reports are working fine for me. 

<img width="1336" alt="Screenshot 2023-03-27 at 5 59 17 PM" src="https://user-images.githubusercontent.com/31363128/227942064-eb3add44-1fff-4ecb-9027-0c1474a4d775.png">

From the information you shared, it seems like you are still on v13. I recommend that you migrate to v14, as the app has been separated from ERPNext since.

**Comment by pateljannat** [comment]
@muslimfaisal Both reports are working fine for me. 

<img width="1336" alt="Screenshot 2023-03-27 at 5 59 17 PM" src="https://user-images.githubusercontent.com/31363128/227942064-eb3add44-1fff-4ecb-9027-0c1474a4d775.png">

From the information you shared, it seems like you are still on v13. I recommend that you migrate to v14, as the app has been separated from ERPNext since.

**Comment by muslimfaisal** [comment]
@pateljannat , thank you so much.
We will upgrade our test system and give it a go.
