### ISSUE TITLE
Naming series is not working for Instructor doctype in Education module

### ISSUE THREAD

**Issue by iqbaltld** [frappe/education#136]
I was attempting to create an ‘Instructor’ within the Education module. I customized the doctype to utilize a different naming series and updated the ‘Document Naming Settings’ by incorporating the necessary naming series. However, when I saved the instructor, the ‘ID’ was assigned the same value as the ‘instructor name’ I provided, instead of following the specified naming series. Interestingly, when I followed the same steps for the ‘Student’ doctype, it worked seamlessly without any issues.

**Comment by RitvikSardana** [comment]
Yes that is because, in Education Settings there is a Select Field called "instructor_created_by", naming rule is defined by this field.

So you can change it from the 3 options which are given in Education Settings.


<img width="1325" alt="Screenshot 2023-11-02 at 2 54 37 PM" src="https://github.com/frappe/education/assets/65544983/984a795b-1c17-45ed-a805-31ca170d57f5"> 

####

**By Naming Series**
<img width="1339" alt="Screenshot 2023-11-02 at 2 55 20 PM" src="https://github.com/frappe/education/assets/65544983/e8d85cee-ef11-41bd-87a1-1a500726861a">


####
**By Full Name**
<img width="380" alt="Screenshot 2023-11-02 at 2 56 55 PM" src="https://github.com/frappe/education/assets/65544983/2b8aba80-2df3-40c5-8fa9-e4e56317fbd2">
